export const COLLECTIONS = {
  users: "users",
  gyms: "gyms",
  openMats: "openMats",
  rsvps: "rsvps",
  checkins: "checkins",
  favorites: "favorites",
  notifications: "notifications",
  reports: "reports",
  waitlistLeads: "waitlistLeads",
  gymLeads: "gymLeads",
  gymMemberships: "gymMemberships",
  beltPromotions: "beltPromotions",
  gymClasses: "gymClasses",
  classOccurrences: "classOccurrences",
  classRsvps: "classRsvps",
  classJournals: "classJournals",
  instructorRatings: "instructorRatings",
  forumQuestions: "forumQuestions",
  forumAnswers: "forumAnswers",
  conversations: "conversations",
  messages: "messages",
  conversationParticipants: "conversationParticipants",
  channelReadStates: "channelReadStates",
  userBlocks: "userBlocks",
  messageReports: "messageReports",
} as const;

export type CollectionName = (typeof COLLECTIONS)[keyof typeof COLLECTIONS];
